---
language: python
services: docker

env:
  - php_version: '7.3'
  - php_version: '7.2'
  - php_version: '7.1'
  - php_version: '5.6'

install:
  # Install Ansible.
  - pip install ansible docker
  - export ANSIBLE_FORCE_COLOR=true

  # Install role dependencies.
  - ansible-galaxy install -r requirements.yml

script:
  # Build the container.
  - ansible-playbook --extra-vars="@vars/${php_version}.yml" main.yml

  # Verify the container runs and has the correct PHP version.
  - docker run -d --name=php-apache -p 8080:80 geerlingguy/php-apache:${php_version} /usr/sbin/apache2ctl -D FOREGROUND
  - docker exec php-apache php -v | grep ${php_version}
  - curl http://localhost:8080/

deploy:
  provider: script
  script: bash docker-push
  on:
    branch: master
